core/urls.py
from django.urls import path
from .views import evaluations, evaluation, edit_evaluation, evaluation_view_form

urlpatterns = [
    path('', evaluations, name='evaluations'),
    path('<slug:slug>/', evaluation, name='evaluation'),
    path('edit/<int:pk>/', edit_evaluation, name='edit_evaluation'),
    path('evaluate/<int:pk>/', evaluation_view_form, name='submit_evaluation'),
    # path('',views.EvaluationModuleView.as_view(),name='evaluation_module_view'),
    # path('<int:id>',views.EvaluationSingleView.as_view(),name='evaluation_single_view'),
]

evaluation_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import login_student, logout_student, register_student, student_profile_create, login_qadmin
from qasa_app.views import send_ux_email

urlpatterns = [
                  path('send_ux_email/', send_ux_email, name='send_ux_email'),
                  path('admin/', admin.site.urls),
                  path('', include('core.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('register', register_student, name="register_student"),
                  path('login-qadmin', login_qadmin, name="login_qadmin"),

                  path('evaluation-admin/', include('qasa_app.urls')),
                  path('profile/student/<int:pk>/create', student_profile_create, name="student_profile_create"),

                  # path('__debug__/', include('debug_toolbar.urls')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "pages.views.page_not_found_view"

qasa_app/urls.py
from django.urls import path

from .views import evaluation_reports_generated_list, view_schools, evaluation_report, view_academic_years, \
    create_academic_year, create_school, delete_academic_year, delete_school, school_with_departments, \
    create_department, delete_department, view_department, view_program, view_course, create_program, create_course, \
    edit_course, delete_course, edit_department, setup_evaluation, analytic_dashboard, view_all_evaluations, \
    edit_school, edit_program, delete_evaluation, edit_evaluation, student_dashboard, add_facilitator, edit_facilitator, \
    delete_facilitator, view_facilitators

urlpatterns = [



    path('dashboard/', analytic_dashboard, name='analytic_dashboard'),

    path('courses/', create_course, name='create_course'),
    path('courses/<slug:slug>/', view_course, name='view_course'),
    path('courses/<slug:slug>/edit', edit_course, name='edit_course'),
    path('courses/<slug:slug>/delete', delete_course, name='delete_course'),

    path('programs/<slug:slug>/', view_program, name='view_program'),
    path('programs/<slug:slug>/edit', edit_program, name='edit_program'),
    path('programs/create', create_program, name='create_program'),

    path('departments/<slug:slug>/', view_department, name='view_department'),
    path('departments/create', create_department, name='create_department'),
    path('department/<int:pk>/delete', delete_department, name='delete_department'),
    path('departments/<slug:slug>/edit', edit_department, name='edit_department'),

    path('facilitators/', view_facilitators, name='view_facilitators'),
    path('facilitators/create', add_facilitator, name='add_facilitator'),
    path('facilitators/<int:pk>/edit', edit_facilitator, name='edit_facilitator'),
    path('facilitators/<int:pk>/delete', delete_facilitator, name='delete_facilitator'),

    path('academic-years/', view_academic_years, name='view_academic_years'),
    path('academic-years/<int:pk>', delete_academic_year, name='delete_academic_year'),
    path('academic-years/create/', create_academic_year, name='create_academic_year'),

    path('schools/', view_schools, name='view_schools'),
    path('schools/create/', create_school, name='create_school'),
    path('schools/<slug:slug>/edit/', edit_school, name='edit_school'),
    path('schools/<int:pk>/', delete_school, name='delete_school'),
    path('schools/<slug:slug>/', school_with_departments, name='school_with_departments'),

    path('evaluations/', view_all_evaluations, name='view_all_evaluations'),
    path('evaluation/setup/', setup_evaluation, name='setup_evaluation'),
    path('evaluation/report/', evaluation_reports_generated_list, name='evaluation_reports_generated_list'),
    path('evaluation/reports/<slug:slug>', evaluation_report, name='evaluation_report'),
    path('evaluation/<slug:slug>/delete', delete_evaluation, name='delete_evaluation'),
    path('evaluation/<slug:slug>/edit', edit_evaluation, name='edit_evaluation'),









]

core/models.py
import uuid
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from accounts.models import Student


# Create your models here.


class AcademicYear(models.Model):
    academic_year = models.CharField(max_length=255, null=False, blank=False)

    def __str__(self):
        return self.academic_year


class Evaluation(models.Model):
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)
    facilitator = models.ForeignKey('Facilitator', on_delete=models.CASCADE)
    course = models.OneToOneField('Course', on_delete=models.CASCADE)
    description = models.CharField(max_length=150, blank=True, null=True)
    aggregated_score_computed_value = models.FloatField(default=0, editable=False)
    slug = models.SlugField(unique=True, default=uuid.uuid4)
    deadline = models.DateTimeField(null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Evaluation Reports'

    @property
    def check_active_status(self):
        if self.deadline > timezone.now():
            return True
        else:
            return False

    def __str__(self):
        return f"{self.course.course_code} - {self.course.name} - {self.course.course_group.upper()[0:1]}- {self.course.program} "

    def save(self, *args, **kwargs):
        # slug_value = self.course.name + '-' + str(self.facilitator.staff_id) + '-' + self.course.course_group
        # self.slug = slugify(slug_value)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('evaluation_report', kwargs={'slug': self.slug})


class EvaluationSubmission(models.Model):
    class FeedbackChoices(models.IntegerChoices):
        NOT_APPLICABLE = 0
        STRONGLY_DISAGREE = 1
        DISAGREE = 2
        MODERATELY_DISAGREE = 3
        AGREE = 4
        STRONGLY_AGREE = 5

    evaluationInfo = models.ForeignKey(Evaluation, blank=True, null=True, on_delete=models.CASCADE,
                                       related_name='submitted_evaluations')

    curriculum_feedback_beginning_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    curriculum_feedback_course_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    curriculum_feedback_lecture_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    curriculum_feedback_outcomes_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    curriculum_feedback_procedures_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    curriculum_feedback_books_answer = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    attendance_schedule = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    attendance_punctuality = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    attendance_presence = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    delivery_enthusiasm = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_sequence = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_organization = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_clarity = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_contents = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_responsiveness = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_achievements = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_innovation = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    delivery_theory_practices = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    assignments_relevance = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    assignments_promptitude = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    assignments_feedback = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    assignments_guidance = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    interaction_availability = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    interaction_help = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    interaction_fairness = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    environment_classroom_size = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_seats = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_audio_visual_equip = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_public_address = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_books = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_computers = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_internet = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_air_conditioning = models.IntegerField(choices=FeedbackChoices.choices, default=None)
    environment_secretariat = models.IntegerField(choices=FeedbackChoices.choices, default=None)

    slug = models.SlugField(unique=True, default=uuid.uuid4)
    submitter = models.ForeignKey(Student, blank=True, null=True, on_delete=models.PROTECT)
    is_evaluated = models.BooleanField(blank=False, null=False, default=False)

    # deadline = models.DateTimeField(null=False,blank=False, default=datetime.datetime)

    def __str__(self):
        return f"{self.evaluationInfo} {self.submitter}"

    def save(self, *args, **kwargs):
        # self.slug = str(self.evaluationInfo) + '-' + str(uuid.uuid4())
        # self.slug = slugify(self.slug[50:])
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('evaluation', args=[self.slug])

    class Meta:
        unique_together = [('submitter', 'evaluationInfo')]


# Organisation Models
class Facilitator(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    staff_id = models.IntegerField(default=0)
    school = models.ForeignKey('School', on_delete=models.SET_NULL, null=True, blank=False)

    def __str__(self):
        return self.first_name + " " + self.last_name + " (" + str(self.staff_id) + ")"


class School(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=255, null=True, blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=250)
    school = models.ForeignKey('School', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, null=True, blank=True, unique=True)
    description = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('view_department', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


class Program(models.Model):
    name = models.CharField(max_length=250)
    department = models.ForeignKey('Department', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, null=True, blank=True, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('view_program', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Course(models.Model):
    choices = (
        ('100', 'Level 100'),
        ('200', 'Level 200'),
        ('300', 'Level 300'),
        ('400', 'Level 400'),
        ('500', 'Level 500'),
        ('600', 'Level 600'),
        ('700', 'Level 700'),
        ('800', 'Level 800'),
    )

    lecture_group = (
        ('day', 'Day'),
        ('evening', 'Evening'),
        ('weekend', 'Weekend'),
    )

    name = models.CharField(max_length=250)
    course_code = models.CharField(max_length=10)
    program = models.ForeignKey('Program', on_delete=models.CASCADE)
    level = models.CharField(default='', max_length=15, choices=choices)
    course_group = models.CharField(default='', max_length=15, choices=lecture_group)
    facilitator = models.ForeignKey('Facilitator', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, default=uuid.uuid4)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name + " " + self.course_code + " (" + str(self.level) + ")" + '–' + self.course_group.upper()[
                                                                                         0:1] + '-' + str(self.program)

    def get_absolute_url(self):
        return reverse('view_course', kwargs={'slug': self.slug})

    # def clean(self):
    #     exists = Course.objects.filter(name=self.name, level=self.level, course_group=self.course_group,
    #                                    facilitator=self.facilitator)
    #     # slug_value = self.name + '-' + str(self.course_group) + '-' + str(uuid.uuid4())
    #
    #     if exists:
    #         raise ValidationError({'name': "Course with same specific details exists"})

    def save(self, *args, **kwargs):
        # try:

        count: int = 0
        self.full_clean()

qasa_app/models.py
from django.db import models

# Create your models here.

qasa_app/templates/qasa_app/department/create_department.html
{% extends 'index.html' %}

{% block content %}
   <div class="container">
     <form method="post" action="">
{% csrf_token %}
         {% if form.errors %}
         {% for error in form.errors %}
             <div class="alert alert-light-danger border-0 mb-4" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
            <strong>Error!</strong> {{ error }}
                 </button>
        </div>
             {% endfor %}
         {% endif %}
    <h5 class="mt-4">Add New Department</h5>
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
   </div>
{% endblock %}

qasa_app/templates/qasa_app/department/department.html
{% extends 'index.html' %}

{% block content%}
   <div class="layout-px-spacing">

                <div class="row layout-top-spacing" id="cancel-row">


                    <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                        <div class="widget-content widget-content-area br-6">

 <div class="row">
      <h5 class="col-10"> {{ department }}

   </h5>
      <div class="col-2 align-right float-right justify-content-right">
          <a href="{% url 'create_program' %}" class="btn btn-warning  mb-4"> + Add Program</a>
      </div>
 </div>




  <ul class="list-group">
  <li class="list-group-item list-group-item-action bg-warning">Programs</li>
    {% for program in department.program_set.all %}
        <li class="list-group-item">
            <a href="{{ program.get_absolute_url }}">{{ program }}</a>

        <span class="ml-3 d-block float-right">
                    <a href="{% url 'edit_program' program.slug %}" class="text-info">
                    <svg xmlns="http://www.w3.org/2000/svg"  width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>

                    </a>

               <a href="" class="text-danger" data-toggle="modal" data-target="#deletemodal-{{ program.id }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 icon"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                    </a>
                </span>
        </li>


        <div class="modal fade" id="deletemodal-{{ program.id }}" tabindex="-1" role="dialog" aria-labelledby="deletemodallabel-{{ program.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deletemodallabel-{{ program.id }}">Permanent Action</h5>

            </div>
            <div class="modal-body">
                <form action="{% url 'delete_course' program.slug %}" method="post">
                                                    {% csrf_token %}
<h5>Are you sure you want to delete? {{ program }}</h5>



            <div class="modal-footer">
                <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Discard</button>
               <button type="submit" class="btn btn-danger">Delete</button>
            </div>
             </form>
                   </div>
        </div>
    </div>
</div>


    {% endfor %}
  </ul>

</div>
                    </div>
                </div>
   </div>




{% endblock %}

qasa_app/templates/qasa_app/department/departments.html
{%extends 'index.html'%} {%load static%}
{% block content %}

<div class="layout-px-spacing">


                <div class="row layout-top-spacing" id="cancel-row">
                    <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                        <div class="widget-content widget-content-area br-6">
                            <div class="table-responsive mb-4 mt-4">
                                <div id="multi-column-ordering_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">

                                    <div class="row"><div class="col-sm-12">

                                        <a href="{% url 'create_department' %}" class="btn btn-success float-right mb-4"> + Add Department</a>

                                        <table id="multi-column-ordering" class="table table-hover dataTable" style="width: 100%;" role="grid" aria-describedby="multi-column-ordering_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="multi-column-ordering" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 385px;">ID</th>
                                            <th class="sorting" tabindex="0" aria-controls="multi-column-ordering" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 385px;">Department</th>
                                            <th class="sorting" tabindex="0" aria-controls="multi-column-ordering" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 385px;">Actions</th>


                                    </thead>
                                    <tbody>

{% if departments %}
    {% for department in departments %}
                                    <tr role="row">
                                            <td><a>{{ department.id}}</a></td>
                                            <td><a href="{{ department.get_absolute_url }}">{{ department}}</a></td>
                                            <td>

                                                   <a href="{% url 'edit_department' department.slug %}" class="text-info">
                    <svg xmlns="http://www.w3.org/2000/svg"  width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>

                    </a>



                                                <a href="" class="text-danger" data-toggle="modal" data-target="#deletemodal-{{ department.id }}">

                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 icon"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                </a>

                                            </td>


                                        </tr>


        <div class="modal fade" id="deletemodal-{{ department.id }}" tabindex="-1" role="dialog" aria-labelledby="deletemodallabel-{{ department.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deletemodallabel-{{ department.id }}">Permanent Action</h5>

            </div>
            <div class="modal-body">
                <form action="{% url 'delete_department' department.id %}" method="post">
                                                    {% csrf_token %}
                        <h5>Are you sure you want to delete? {{ department }}</h5>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Discard</button>
               <button type="submit" class="btn btn-danger">Delete</button>
            </div>
             </form>
                   </div>
        </div>
    </div>
</div>


{% endfor %}
                                    {% endif %}

                                    </tbody>
                                    <tfoot>
{#                                        <tr><th rowspan="1" colspan="1">Name</th><th rowspan="1" colspan="1">Position</th><th rowspan="1" colspan="1">Office</th><th rowspan="1" colspan="1">Age</th><th rowspan="1" colspan="1">Start date</th><th rowspan="1" colspan="1">Salary</th></tr>#}
                                    </tfoot>
                                </table>
                                    </div>
                                    </div>
                                    <div class="row"><div class="col-sm-12 col-md-5">
                                        <div class="dataTables_info" id="multi-column-ordering_info" role="status" aria-live="polite">Showing page 1 of 4</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="multi-column-ordering_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="multi-column-ordering_previous"><a href="#" aria-controls="multi-column-ordering" data-dt-idx="0" tabindex="0" class="page-link"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg></a></li><li class="paginate_button page-item active"><a href="#" aria-controls="multi-column-ordering" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="multi-column-ordering" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="multi-column-ordering" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="multi-column-ordering" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item next" id="multi-column-ordering_next"><a href="#" aria-controls="multi-column-ordering" data-dt-idx="5" tabindex="0" class="page-link"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg></a></li></ul></div></div></div></div>
                            </div>
                        </div>
                    </div>
                </div>

                </div>
{%endblock content%}

qasa_app/templates/qasa_app/department/edit_department.html
{% extends 'index.html' %}

{% block content %}
   <div class="container">
     <form method="post" action="">
{% csrf_token %}
         {% if form.errors %}
         {% for error in form.errors %}
             <div class="alert alert-light-danger border-0 mb-4" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg> ... </svg></button>
            <strong>Error!</strong> {{ error }}
                 </button>
        </div>
             {% endfor %}
         {% endif %}
    <h5 class="mt-4">Update Department</h5>
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
   </div>
{% endblock %}